# Generated by Django 5.0.3 on 2024-03-27 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0008_auto_20210519_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='give_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 19, 12, 15, 892655)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='take_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 19, 12, 15, 892523)),
        ),
    ]
